version: '3.8'

services:
  backend:
    # build: .
    image: kbao17122006/uniadmit-backend:latest
    container_name: uniadmit-backend
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
    volumes:
      - ./private:/app/private
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped
